### PR TITLE
Fixed the issue #180 (Current score overlaps ultimate gauge)

### PR DESCRIPTION
**Pull request by Verssae**
* Modify the position of the score objects in the prepHighscore () and prepLevel () functions of the scoreboard class, and rename the UI to be more user friendly by adding "SCORE:", "LEVEL:".
* Take updateUltimateGauge () function of gamefunction as scoreboard as argument and do not overlap by considering relative position with scores. 
* Also, to increase the visual effect, change the color of the gauge gauge to cyan, change it to yellow when it is full, and "POWER SHOT (X)" above the gauge.
* #180

### CODE REVIEW

**Comment by Taewan-P** [comment]
@Verssae Pull Request #197 에서 이미 해결되었습니다(일부...?)

**Comment by Verssae** [comment]
@Taewan-P I do not know where the 'distracting UI improvements' mentioned in # 197 is, but I have written in this article that you see a lot of changes, as you can see in # 217 of the code changes. Of course, the changes made at # 197 are reflected. Please check again.

**Comment by Taewan-P** [comment]
@Verssae 흠... 그렇군요
저는 Pull Request #197 에 보시면 Issue #194 를 통하여 산만한 UI를 개선하였다고 해서 일부 해결되었다고 말해드린겁니다...

**Comment by Taewan-P** [comment]
궁게이지 색깔이 바뀐거 말고는 중복이 아닐까 싶어서... 보니깐 Issue 자체가 약간 비슷한것 같네요 :)
ref) Issue #180 Issue #194

**Pull request merged**
