### PR TITLE
fix conflict

### PR DESCRIPTION
**Pull request by jil8885**
not delete that imports animation code(to execute, you should deactivate all codes about animation or explosion)
add shooting bullets continuously when player push spacebar

### CODE REVIEW

**Comment by Taewan-P** [comment]
@inureyes 교수님 위에 저친구말대로 from animations import Explosion 모듈이 없다고 뜹니다. 혹시 해결방법이 있나요??

**Comment by Verssae** [comment]
스페이스 바 누르면 튕기는데요...?

**Comment by inureyes** [comment]
제가 몽땅 패치해 두었으니 안 튕길겁니다.

신정규 드림


'Everything looks different on the other side'
                     -Ian Malcomm, from Michael Crichton's 'The Jurassic Park'

Jeongkyu Shin, Ph.D. 

Founder, Lablup Inc. - Make AI accessible
http://www.lablup.com

Leader,  NeedlWorks and Tatter Network Foundation (http://www.needlworks.org / http://www.textcube.org)

E@ : inureyes at gmail.com
T@ : @inureyes / H@ : http://jkshin.nubimaru.com

**Comment by jil8885** [comment]
오 교수님 감사합니다

**Pull request merged**
