### PR TITLE
#203 add stage clear sound effect 

### PR DESCRIPTION
**Pull request by BeautifulTommorow**
add stage clear sound effect

### CODE REVIEW

**Comment by StillnessFate** [comment]
Please correct the conflicting files.

**Comment by Taewan-P** [comment]
@BeautifulTommorow .DS_Store 파일 지워주세요!

**Comment by Taewan-P** [comment]
#203

**Comment by StillnessFate** [comment]
Conflicts must be resolved.

**Comment by StillnessFate** [comment]
@BeautifulTommorow @inureyes This code is indented using tab!

**Pull request merged**
