### PR TITLE
Resolve issue #102

### PR DESCRIPTION
**Pull request by Keunmo**
issue #102 works well, able to merge.

but have few flaws.
1. need to make item icon background clear -> FIXED
2. after a few time after eating the speed item, the speed of the player should be normal again. -> DELETE SPEED ITEM

### CODE REVIEW

**Comment by StillnessFate** [comment]
- Do not delete the .editorconfig file. This is the code style configuration file used by the code editor
- You are indenting the code using tabs. This does not fit the project's current code style. And using two indent styles for a single source code results in an error.
- The four added images are not transparent.
- Line 2 of gameFunctions.py: Follow the PEP 3 guidelines.

Due to the use of incorrect indentation, the large area of ​​code is highlighted, making detailed review difficult.

**Comment by Keunmo** [comment]
make item images transparent.
delete speed item.

**Comment by Keunmo** [comment]
item drop speed changed

**Comment by Keunmo** [comment]
fix conflicts with updated one.

**Comment by StillnessFate** [comment]
@Keunmo Why does time.sleep(1)?

**Comment by Keunmo** [comment]
where? 내 코드에 그런거 없는데?

**Comment by StillnessFate** [comment]
@Keunmo gameFunctions.py 363행... 자기가 작성한 코드도 모르면 어쩜.. 보라고 행에다가 직접 리뷰들도 써놨는데

**Comment by StillnessFate** [comment]
cff0534 gameFunctions.py line 363. It was revised after I wrote the review.

**Comment by StillnessFate** [comment]
An unnecessary prepShips method call degrades performance.

**Comment by inureyes** [comment]
@Keunmo Need to recheck conflicts. (many changes since its request..)

**Comment by Keunmo** [comment]
fix conflicts.. 이제 머지..?

**Pull request merged**
